
command_timeout = 2000


[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 6


[hostname]
ssh_only = false
format = "[$ssh_symbol](bold blue) on [$hostname](bold red) "
trim_at = ".companyname.com"
disabled = false
